config/routes.rb
Rails.application.routes.draw do
  Rails.application.routes.default_url_options[:host] = 'localhost:3000'
  
  root 'parkings#index'

  resources :parkings do
    resources :place_rents, only: [:new, :create]
  end
  resources :place_rents, only: [:show, :index, :destroy]
  resources :cars

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'register' => 'accounts#new'
  post 'register' => 'accounts#create'
  delete 'logout' => 'sessions#destroy'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
 

end

app/models/place_rent.rb
class PlaceRent < ActiveRecord::Base
  belongs_to :car
  belongs_to :parking
  validates :starts_at, :ends_at, :parking, :car, presence: true
  before_save :set_price

  def close_parking
    self.ends_at = Time.now if ends_at >= Time.now
  end

  def to_param
    "#{self.id}-" + ('a'..'z').to_a.shuffle[0, 8].join
  end


  def calculate_price
    start_d = starts_at.beginning_of_hour
    end_d = ends_at
    day_p = (parking.day_price).round(2)
    hour_p = (parking.hour_price).round(2)

    unless end_d == end_d.beginning_of_hour
      end_d = (end_d + 1.hour).at_beginning_of_hour
    end

    if end_d.to_date == start_d.to_date
      (((end_d - start_d) / 1.hour).round) * parking.hour_price
    else
      @start_day_hours = (((start_d.at_end_of_day - start_d) / 1.hour).round)
      @days = (end_d.at_beginning_of_day - (start_d + 1.days).at_beginning_of_day).to_i / 1.day
      @end_day_hours = (((end_d - end_d.at_beginning_of_day) / 1.hour).round)
      if @start_day_hours == 24
        @days += 1
        @start_day_hours = 0
      end
      if @end_day_hours == 24
        @days += 1
        @end_day_hours = 0
      end
      ((@days * day_p) + (@start_day_hours + @end_day_hours) * hour_p).round(2)
    end
  end
  
  private

  def set_price
    self.price = calculate_price
  end
end

app/controllers/place_rents_controller.rb
class PlaceRentsController < ApplicationController
  before_action :require_login
  before_action :find_place_rent, only: [:show, :edit, :update, :destroy]
  
  def index
    @place_rents = PlaceRent.all
  end

  def show
    
  end

  def new
    @place_rent = PlaceRent.new
    @cars = current_person.cars
  end

  def edit
    
  end

  def create
    @place_rent = PlaceRent.new(place_rent_params)
    @place_rent.car = Car.find(place_rent_params[:car_id])
    @place_rent.parking = Parking.find(params[:parking_id])
    if @place_rent.save
      redirect_to @place_rent, notice: 'You have successfully rented the place.'
    else
      render :new
    end
  end

  def update
    if @place_rent.update(place_rent_params)
      redirect_to @place_rent, notice: 'Place rent was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @place_rent.destroy
    redirect_to place_rents_url, notice: 'Place rent was successfully deleted.'
  end

  private
  
  def find_place_rent
    @place_rent = PlaceRent.find(params[:id])
  end

  def place_rent_params
    params.require(:place_rent).permit(:car_id, :starts_at, :ends_at)
  end
end

app/helpers/place_rents_helper.rb
module PlaceRentsHelper
end

app/views/place_rents/_form.html.erb
<%= form_for @place_rent,  url: parking_place_rents_path do |f| %>
  <% if @place_rent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place_rent.errors.count, "error") %> prohibited this place_rent from being saved:</h2>

      <ul>
      <% @place_rent.errors.full_messages.each do |message| %>
        <li class='alert alert-warning'><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :starts_at %><br>
   <%= f.datetime_select :starts_at, :ampm => true %>
  </div>
  <div class="field">
    <%= f.label :ends_at %><br>
    <%= f.datetime_select :ends_at, :ampm => true %>
  </div>
  <div class="field">
    <%= f.label :car_id %><br>
    <%= f.collection_select(:car_id, current_person.cars, :id, :car_model_registration) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/place_rents/edit.html.erb
<%- title "rent a place" %>
<h1>Edit Rental</h1>

<%= render 'form' %>

<p><%= link_to 'Show', @place_rent %> </p>
<p><%= link_to 'Back to parkings list', parkings_path %></p>
<p><%= link_to 'View all rentals', place_rents_path %></p>

app/views/place_rents/index.html.haml
- title "Place rentals"
.row
  .col-xs-12
    .panel.panel-default
      .panel-heading
        %h2 Rents
      .panel-body
        %table.table
          %thead
            %tr
              %th Start Date
              %th End Date
              %th Price
              %th{:colspan => "3"}
          %tbody
            - @place_rents.each do |place_rent|
              %tr
              %td= place_rent.starts_at.to_s(:long_ordinal)
              %td= place_rent.ends_at.to_s(:long_ordinal)
              %td= number_to_currency(place_rent.price, unit:"€")
              %td= link_to 'Show', place_rent_path(place_rent)
              %td= link_to 'Show Car', car_path(place_rent.car)
              %td= link_to 'Show Parking', parking_path(place_rent.parking)
      .panel-footer

app/views/place_rents/new.html.erb
<%- title "Rent a place" %>
<h1>Rent a place</h1>

<%= render 'form' %>
<br>
<p><%= link_to 'Back to parkings list', parkings_path %></p>
<p><%= link_to 'View all rentals', place_rents_path %></p>

app/views/place_rents/show.html.erb
<%- title "Place rental" %>
<div class="row">
  <div class="col-xs-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2>View Rental Details</h2>
      </div>
      <div class="panel-body">
        <p>
          <strong>Start date:</strong>
          <%= @place_rent.starts_at.to_s(:long_ordinal) %>
        </p>

        <p>
          <strong>End date:</strong>
          <%= @place_rent.ends_at.to_s(:long_ordinal) %>
        </p>
        <p>
          <strong>Price:</strong>
          <%= number_to_currency(@place_rent.price, unit:"€") %>
        </p>
      </div>
      <div class="panel-footer">
        <%= link_to 'Back', place_rents_path %>
      </div>
    </div>
  </div>
</div>