config/routes.rb
Rails.application.routes.draw do
  Rails.application.routes.default_url_options[:host] = 'localhost:3000'
  
  root 'parkings#index'

  resources :parkings do
    resources :place_rents, only: [:new, :create]
  end
  resources :place_rents, only: [:show, :index, :destroy]
  resources :cars

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'register' => 'accounts#new'
  post 'register' => 'accounts#create'
  delete 'logout' => 'sessions#destroy'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
 

end

app/models/parking.rb
class Parking < ActiveRecord::Base
  belongs_to :owner, class_name: :'Person'
  belongs_to :address, dependent: :destroy
  has_many :place_rents
  before_destroy :close_all_parkings

  validates :hour_price, :day_price, presence: true,  numericality: true
  validates :kind, inclusion: { in: %w(outdoor indoor private street), message: "%{value} is not a valid kind" }

  accepts_nested_attributes_for :address, allow_destroy: true

  scope :city_starts_with,   -> (city_name) {  joins(:address).where('addresses.city  like ?', "#{city_name}%") }
  scope :day_price_between,  -> (start_price, end_price) { where('parkings.day_price between ? and ?', start_price, end_price) }
  scope :hour_price_between, -> (start_price, end_price) { where('parkings.hour_price between ? and ?', start_price, end_price) }
  scope :private_parkings,   -> { where(kind: :private) }
  scope :public_parkings,    -> { where("parkings.kind != 'private'") }

  self.per_page = 5

  def self.parking_search(params)
    parkings = Parking.all
    parkings = parkings.city_starts_with(params[:city_name]) if params[:city_name].present?
    unless params[:show_public]  && params[:show_private]
      parkings = parkings.public_parkings if params[:show_public]
      parkings = parkings.private_parkings if params[:show_private]
    end
    parkings = parkings.day_price_between(params[:day_price_from], params[:day_price_to]) if params[:day_price_from].present? && params[:day_price_to].present?
    parkings = parkings.hour_price_between(params[:hour_price_from], params[:hour_price_to]) if params[:hour_price_from].present? && params[:hour_price_to].present?
    parkings
  end

  private

  def close_all_parkings
    place_rents.each do |place_rent|
      place_rent.close_parking
      place_rent.save
    end
  end
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  before_action :find_parking, only: [:show, :edit, :update, :destroy]

  def index
    @search_params = search_params
    if params.key?('commit')
      @parkings = Parking.parking_search(search_params).page(params[:page])
    else
      @parkings = Parking.all.page(params[:page])
    end
  end

  def show
  end

  def new
    @parking = Parking.new
    @parking.build_address
  end

  def create
    @parking = Parking.new(parking_params)
    if @parking.save
      redirect_to @parking, notice: t('parking_create_success')
    else
      render :new
    end
  end

  def edit
  
  end

  def update
    if @parking.update(parking_params)
      redirect_to @parking, notice: t('parking_update_success')
    else
      render :edit
    end
  end
  
  def destroy
    @parking.destroy
    redirect_to action: :index, notice: t('parking_success_delete')
  end

  private

  def find_parking
    @parking = Parking.find(params[:id])
  end

  def parking_params
    params.require(:parking).permit(:kind, :places, :hour_price, :day_price, address_attributes: [:city, :zip_code, :street])
  end

  def search_params
    params.permit(:hour_price_from, :hour_price_to, :day_price_from, :day_price_to, :city_name, :show_private, :show_public)
  end

  def record_not_found
    redirect_to parkings_url, alert: t('parking_not_found')
  end
end

app/helpers/parkings_helper.rb
module ParkingsHelper
end

app/views/parkings/_form.html.erb
<%= form_for @parking,  html: { class: 'form-horizontal' } do |f| %>
  <% if @parking.errors.any? %>
    <div>
      <h2>
        <%= pluralize(@parking.errors.count, "error") %> errors!
      </h2>
      <ul>
        <% @parking.errors.full_messages.each do |msg| %>
          <li class='alert alert-warning'><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :kind , class: 'col-sm-2 control-label' %>
    <div class='col-sm-10'>
      <%= f.text_field :kind, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :places , class: 'col-sm-2 control-label' %>
    <div class='col-sm-10'>
    <%= f.number_field :places, step: 1, class: 'form-control'  %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :hour_price, class: 'col-sm-2 control-label' %>
    <div class='col-sm-10'>
      <div class='input-group'>
        <div class="input-group-addon">€</div>
         <%= f.number_field :hour_price, step: 0.01, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :day_price, class: 'col-sm-2 control-label' %>
    <div class='col-sm-10'>
      <div class='input-group'>
        <div class="input-group-addon">€</div>
         <%= f.number_field :day_price, step: 0.01, class: 'form-control' %>
      </div>
    </div>
  </div>
  <%= f.fields_for :address do |ff| %>
    <div class="form-group">
      <%= ff.label :city , class: 'col-sm-2 control-label' %>
      <div class='col-sm-10'>
        <%= ff.text_field :city, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= ff.label :street , class: 'col-sm-2 control-label' %>
      <div class='col-sm-10'>
        <%= ff.text_field :street, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= ff.label :zip_code , class: 'col-sm-2 control-label' %>
      <div class='col-sm-10'>
        <%= ff.text_field :zip_code, class: 'form-control' %>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/parkings/_search_form.erb
<%= form_tag({controller: "parkings", action: "index"}, method: "get", id: 'parking_search', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag "day_price_from", nil, class: 'col-sm-2 control-label_tag' %>
    <div class='col-sm-4'>
      <div class='input-group'>
        <div class="input-group-addon">€</div>
          <%= number_field_tag "day_price_from", nil, step: 0.01, class: 'form-control', value: @search_params[:day_price_from] || ""  %> 
      </div>
    </div>
    <%= label_tag "day_price_to", nil, class: 'col-sm-2 control-label_tag' %>
    <div class='col-sm-4'>
      <div class='input-group'>
        <div class="input-group-addon">€</div>
          <%= number_field_tag :day_price_to, nil, step: 0.01, class: 'form-control', value: @search_params[:day_price_to] || ""  %> 
      </div>
    </div>
  </div>

    <div class="form-group">
    <%= label_tag "hour_price_from", nil, class: 'col-sm-2 control-label_tag' %>
    <div class='col-sm-4'>
      <div class='input-group'>
        <div class="input-group-addon">€</div>
          <%= number_field_tag "hour_price_from", nil, step: 0.01, class: 'form-control', value: @search_params[:hour_price_from] || "" %> 
      </div>
    </div>
    <%= label_tag "hour_price_to", nil, class: 'col-sm-2 control-label_tag' %>
    <div class='col-sm-4'>
      <div class='input-group'>
        <div class="input-group-addon">€</div>
          <%= number_field_tag "hour_price_to", nil, step: 0.01, class: 'form-control', value: @search_params[:hour_price_to] || "" %> 
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= label_tag "city_name", nil, class: 'col-sm-2 control-label_tag' %>
    <div class='col-sm-10'>
      <%= text_field_tag "city_name", nil, class: 'form-control', value: @search_params[:city_name] || ""  %>
    </div>
  </div>
  <div class="form-group">
    <%= label_tag "show_private", nil, class: 'col-sm-2 control-label_tag' %>
    <div class='col-sm-4'>
      <div class="checkbox">
        <%= check_box_tag "show_private", nil, @search_params[:show_private]   %>
      </div>
    </div>
    <%= label_tag "show_public", nil, class: 'col-sm-2 control-label_tag' %>
    <div class='col-sm-4'>
      <div class="checkbox">
        <%= check_box_tag "show_public", nil, @search_params[:show_public] %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= submit_tag 'Search Parkings', class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/parkings/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2>Editing Parking</h2>
      </div>
      <div class="panel-body">
         <%= render 'form' %>
      </div>
      <div class="panel-footer">
        <%= link_to 'Show', @parking %> |
        <%= link_to 'Back', parkings_path %>
      </div>
    </div>
  </div>
</div>

app/views/parkings/index.html.haml
.row
  .col-xs-12
    .panel.panel-default
      .panel-heading
        %h2 Search Parkings
      .panel-body
        = render 'search_form'
    .panel.panel-default
      .panel-heading
        %h2 Parking List
      .panel-body
        = page_entries_info @parkings
      %table.table
        %thead
          %tr
            %th City
            %th Places
            %th Hourly Price
            %th Daily Price
            %th{:colspan => "4"}
        %tbody
          - @parkings.each do |parking|
            %tr
              %td
                - if parking.address.present?
                  = parking.address.city
              %td= parking.places
              %td= number_to_currency(parking.hour_price, unit:"€")
              %td= number_to_currency(parking.day_price, unit:"€")
              %td= link_to 'Show', parking
              %td= link_to 'Edit', edit_parking_path(parking)
              %td= link_to 'Delete', parking, method: :delete, data: { confirm: 'Are you sure?' }
              %td= link_to 'Rent a place', new_parking_place_rent_path(parking)
      .panel-footer
        = will_paginate @parkings
        = button_to 'Create a New Parking', new_parking_path, class: 'btn btn-default', method: :get

app/views/parkings/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2>Add a new Parking</h2>
      </div>
      <div class="panel-body">
        <%= render partial: "form", locals: {parking: @parking} %>
      </div>
      <div class="panel-footer">
        <%= link_to 'Back', parkings_path %>
      </div>
    </div>
  </div>

app/views/parkings/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2>Parking Details</h2>
      </div>
      <div class="panel-body">
        <p>Kind of Parking: <%= @parking.kind %></p>
        <p>Places: <%= @parking.places %></p>
        <p>Hourly Price: <%= number_to_currency(@parking.hour_price, unit:"€") %></p>
        <p>Daily Price: <%= number_to_currency(@parking.day_price, unit:"€") %></p>
        <% if @parking.address.present? %>
          <h3>Parking Address</h3>
          <p>City: <%= @parking.address.city %></p>
          <p>Street: <%= @parking.address.street %></p>
          <p>Zip Code: <%= @parking.address.zip_code %></p>
        <% end %>
        <% if @parking.owner.present? %>
          <h3>Owner</h3>
          <p>First Name: <%= @parking.owner.first_name %></p>
          <p>Last Name: <%= @parking.owner.last_name %></p>
        <% end %>
        </div>
      <div class="panel-footer">
        <%= link_to 'Back', parkings_path %>
      </div>
    </div>
  </div>