config/routes.rb
Rails.application.routes.draw do
  Rails.application.routes.default_url_options[:host] = 'localhost:3000'
  
  root 'parkings#index'

  resources :parkings do
    resources :place_rents, only: [:new, :create]
  end
  resources :place_rents, only: [:show, :index, :destroy]
  resources :cars

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'register' => 'accounts#new'
  post 'register' => 'accounts#create'
  delete 'logout' => 'sessions#destroy'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
 

end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :owner, class_name: :'Person'
  has_many :place_rents, dependent: :destroy
  validates :model, :registration_number, :owner, presence: true
  dragonfly_accessor :image
  validates_size_of :image, maximum: 200.kilobytes, message:'should not be greater than 200 KB', if: :image_changed?
  validates_property :format, of: :image, in: [:jpeg, :jpg, :png, :bmp], case_sensitive: false, message: 'must be an image file format of .jpeg, .jpg, .png, .bmp', if: :image_changed?

  def car_model_registration
    model + ' - ' + registration_number
  end

  def to_param
    "#{id}-#{model}"
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  before_action :require_login
  before_action :find_car, only: [:show, :edit, :update, :destroy]

  
  def index
    @cars = current_person.cars
  end

  def show
  end

  def new
    @car = current_person.cars.new
  end

  def edit
  end

  def create
    @car = current_person.cars.new(car_params)
    if @car.save
      redirect_to @car, notice: 'Car was successfully created.'
    else
      render :new
    end
  end

  def update
    if @car.update(car_params)
      redirect_to @car, notice: 'Car was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @car.destroy
    redirect_to cars_url, notice: 'Car was successfully deleted.'
  end

  private

  def find_car
    @car = current_person.cars.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:model, :registration_number, :image)
  end

  def record_not_found
    redirect_to cars_url, alert: 'Car not found.'
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h3>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li class='alert alert-warning'><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :registration_number %><br>
    <%= f.text_field :registration_number %>
  </div>
    <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    <% if @car.image_stored? %>
    <div>
      Current Image <br>
       <%= image_tag @car.image.thumb('400x200').url if @car.image_stored? %>
    </div>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.haml
.row
  .col-xs-12
    .panel.panel-default
      .panel-heading
        %h2 Cars List
      .panel-body
        %table.table
          %thead
            %tr
              %th Model
              %th Registration number
              %th{:colspan => "3"}
          %tbody
            - @cars.each do |car|
              %tr
                %td= car.model
                %td= car.registration_number
                %td= link_to 'Show', car
                %td= link_to 'Edit', edit_car_path(car)
                %td= link_to 'Delete', car, method: :delete, data: { confirm: 'Are you sure?' }
      .panel-footer
        = link_to 'New Car', new_car_path

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2>Car Details</h2>
      </div>
      <div class="panel-body">
        <p>
          <strong>Model:</strong>
          <%= @car.model %>
        </p>

        <p>
          <strong>Registration number:</strong>
          <%= @car.registration_number %>
        </p>
      </div>
      <div>
        <%= image_tag @car.image.thumb('400x200').url if @car.image_stored? %>
      </div>
      <div class="panel-footer">
        <%= link_to 'Edit', edit_car_path(@car) %> |
        <%= link_to 'Back', cars_path %>
      </div>
    </div>
  </div>
</div>