config/routes.rb
Rails.application.routes.draw do
  Rails.application.routes.default_url_options[:host] = 'localhost:3000'
  
  root 'parkings#index'

  resources :parkings do
    resources :place_rents, only: [:new, :create]
  end
  resources :place_rents, only: [:show, :index, :destroy]
  resources :cars

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'register' => 'accounts#new'
  post 'register' => 'accounts#create'
  delete 'logout' => 'sessions#destroy'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
 

end

app/views/layouts/_header.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Parking Rentals</a>
        <% if current_person %>
        <p class="navbar-text">
          <%= current_person.full_name %>
        </p>
        <p class="navbar-text">
          <%= link_to 'Log out', logout_path,  method: :delete,  class: 'navbar-link' %>
        </p>
        <% end %>
         <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Language <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li> <%=link_to 'English', url_for( :locale => 'en' )%></li>
              <li> <%=link_to 'German', url_for( :locale => 'de' )%></li>
            </ul>
          </li>
        </ul>
      </div>
      <div id="navbar" class="collapse navbar-collapse pull-right">
      <ul class="nav nav-tabs">
          <li>
            <%= link_to 'Cars', cars_path, class: 'navbar-link' %>
          </li>
          <li>
            <%= link_to 'Parkings', parkings_path, class: 'navbar-link' %>
          </li>
          <li>
            <%= link_to 'Rents', place_rents_path, class: 'navbar-link' %>
          </li>
           <% if !current_person %>
            <li>
              <%= link_to 'Login', login_path, class: 'navbar-link' %>
            </li>
          <% end %>
        </ul>
    </div>
  </div>
</nav>
     

app/views/layouts/_notice.erb
<% if flash[:notice] %>
  <div class="alert alert-info" role="alert" id="info"><%= flash[:notice] %></div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-warning" role="alert" id="notice"><%= flash[:alert] %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? content_for(:title) : params[:controller].titleize %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
     <%= render 'layouts/header' %>
      <div class="container">
      <div class='notice'>
        <%= render 'layouts/notice' %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>